# Generated by Django 4.1.5 on 2023-06-14 21:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fecha",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 6, 14, 21, 9, 44, 202199, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("total", models.IntegerField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("precio", models.IntegerField()),
                ("stock", models.IntegerField()),
                ("imagen", models.CharField(max_length=200)),
                ("oferta", models.BooleanField(default=False)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.categoria"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Detalle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField()),
                ("precio", models.IntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.producto"
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.venta"
                    ),
                ),
            ],
        ),
    ]
