# Generated by Django 4.1.5 on 2023-06-14 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="nombre",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 14, 21, 28, 27, 577790, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
