# Generated by Django 4.1.5 on 2023-06-14 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_producto_nombre_alter_venta_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name="venta",
            name="fecha",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 14, 21, 35, 47, 225424, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
