# Generated by Django 4.2.2 on 2023-06-21 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_venta_fecha_utensilios_sustratos_suculentas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorocion',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='maceteros',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='suculentas',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='sustratos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='utensilios',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 21, 23, 59, 46, 767766, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Cactus',
        ),
        migrations.DeleteModel(
            name='Decorocion',
        ),
        migrations.DeleteModel(
            name='Maceteros',
        ),
        migrations.DeleteModel(
            name='Suculentas',
        ),
        migrations.DeleteModel(
            name='Sustratos',
        ),
        migrations.DeleteModel(
            name='Utensilios',
        ),
    ]
