# Generated by Django 4.2.2 on 2023-06-22 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 0, 53, 51, 981547, tzinfo=datetime.timezone.utc)),
        ),
    ]
