# Generated by Django 4.2.2 on 2023-06-22 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 2, 46, 29, 199223, tzinfo=datetime.timezone.utc)),
        ),
    ]
