# Generated by Django 4.2.2 on 2023-06-22 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 14, 9, 42, 466678, tzinfo=datetime.timezone.utc)),
        ),
    ]
