# Generated by Django 4.2.2 on 2023-06-22 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_venta_fecha_plantas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 14, 18, 34, 155182, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Plantas',
        ),
    ]
