# Generated by Django 4.2.2 on 2023-06-23 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cactus_oferta_alter_decorocion_oferta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 21, 2, 45, 289563, tzinfo=datetime.timezone.utc)),
        ),
    ]
