# Generated by Django 4.2.2 on 2023-06-23 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_descripcion_cactus_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 21, 31, 42, 740074, tzinfo=datetime.timezone.utc)),
        ),
    ]
