# Generated by Django 4.2.2 on 2023-06-24 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_envio',
            field=models.CharField(default='EN PREPARACION', max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 3, 15, 7, 136381, tzinfo=datetime.timezone.utc)),
        ),
    ]
