# Generated by Django 4.2.2 on 2023-06-24 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_venta_estado_envio_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 3, 33, 3, 548429, tzinfo=datetime.timezone.utc)),
        ),
    ]
