# Generated by Django 4.2.2 on 2023-06-24 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cactus',
            name='porcentaje_oferta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_oferta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utensilios',
            name='porcentaje_oferta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 4, 30, 31, 387643, tzinfo=datetime.timezone.utc)),
        ),
    ]
