# Generated by Django 4.2.2 on 2023-06-24 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 5, 3, 35, 657999, tzinfo=datetime.timezone.utc)),
        ),
    ]
