# Generated by Django 4.2.2 on 2023-07-04 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_venta_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorocion',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='maceteros',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='plantas',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='suculentas',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='sustratos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='utensilios',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 3, 13, 37, 409119, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Cactus',
        ),
        migrations.DeleteModel(
            name='Decorocion',
        ),
        migrations.DeleteModel(
            name='Maceteros',
        ),
        migrations.DeleteModel(
            name='Plantas',
        ),
        migrations.DeleteModel(
            name='Suculentas',
        ),
        migrations.DeleteModel(
            name='Sustratos',
        ),
        migrations.DeleteModel(
            name='Utensilios',
        ),
    ]
